# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/doolhof/new_repo/MTO_maze

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/doolhof/new_repo/MTO_maze

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/doolhof/new_repo/MTO_maze/CMakeFiles /home/doolhof/new_repo/MTO_maze//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/doolhof/new_repo/MTO_maze/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MTO_maze

# Build rule for target.
MTO_maze: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MTO_maze
.PHONY : MTO_maze

# fast build rule for target.
MTO_maze/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MTO_maze.dir/build.make CMakeFiles/MTO_maze.dir/build
.PHONY : MTO_maze/fast

include/sources/cell.o: include/sources/cell.cpp.o
.PHONY : include/sources/cell.o

# target to build an object file
include/sources/cell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MTO_maze.dir/build.make CMakeFiles/MTO_maze.dir/include/sources/cell.cpp.o
.PHONY : include/sources/cell.cpp.o

include/sources/cell.i: include/sources/cell.cpp.i
.PHONY : include/sources/cell.i

# target to preprocess a source file
include/sources/cell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MTO_maze.dir/build.make CMakeFiles/MTO_maze.dir/include/sources/cell.cpp.i
.PHONY : include/sources/cell.cpp.i

include/sources/cell.s: include/sources/cell.cpp.s
.PHONY : include/sources/cell.s

# target to generate assembly for a file
include/sources/cell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MTO_maze.dir/build.make CMakeFiles/MTO_maze.dir/include/sources/cell.cpp.s
.PHONY : include/sources/cell.cpp.s

include/sources/maze.o: include/sources/maze.cpp.o
.PHONY : include/sources/maze.o

# target to build an object file
include/sources/maze.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MTO_maze.dir/build.make CMakeFiles/MTO_maze.dir/include/sources/maze.cpp.o
.PHONY : include/sources/maze.cpp.o

include/sources/maze.i: include/sources/maze.cpp.i
.PHONY : include/sources/maze.i

# target to preprocess a source file
include/sources/maze.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MTO_maze.dir/build.make CMakeFiles/MTO_maze.dir/include/sources/maze.cpp.i
.PHONY : include/sources/maze.cpp.i

include/sources/maze.s: include/sources/maze.cpp.s
.PHONY : include/sources/maze.s

# target to generate assembly for a file
include/sources/maze.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MTO_maze.dir/build.make CMakeFiles/MTO_maze.dir/include/sources/maze.cpp.s
.PHONY : include/sources/maze.cpp.s

include/sources/utils.o: include/sources/utils.cpp.o
.PHONY : include/sources/utils.o

# target to build an object file
include/sources/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MTO_maze.dir/build.make CMakeFiles/MTO_maze.dir/include/sources/utils.cpp.o
.PHONY : include/sources/utils.cpp.o

include/sources/utils.i: include/sources/utils.cpp.i
.PHONY : include/sources/utils.i

# target to preprocess a source file
include/sources/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MTO_maze.dir/build.make CMakeFiles/MTO_maze.dir/include/sources/utils.cpp.i
.PHONY : include/sources/utils.cpp.i

include/sources/utils.s: include/sources/utils.cpp.s
.PHONY : include/sources/utils.s

# target to generate assembly for a file
include/sources/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MTO_maze.dir/build.make CMakeFiles/MTO_maze.dir/include/sources/utils.cpp.s
.PHONY : include/sources/utils.cpp.s

src/main_jen.o: src/main_jen.cpp.o
.PHONY : src/main_jen.o

# target to build an object file
src/main_jen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MTO_maze.dir/build.make CMakeFiles/MTO_maze.dir/src/main_jen.cpp.o
.PHONY : src/main_jen.cpp.o

src/main_jen.i: src/main_jen.cpp.i
.PHONY : src/main_jen.i

# target to preprocess a source file
src/main_jen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MTO_maze.dir/build.make CMakeFiles/MTO_maze.dir/src/main_jen.cpp.i
.PHONY : src/main_jen.cpp.i

src/main_jen.s: src/main_jen.cpp.s
.PHONY : src/main_jen.s

# target to generate assembly for a file
src/main_jen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MTO_maze.dir/build.make CMakeFiles/MTO_maze.dir/src/main_jen.cpp.s
.PHONY : src/main_jen.cpp.s

src/motorcontrol.o: src/motorcontrol.cpp.o
.PHONY : src/motorcontrol.o

# target to build an object file
src/motorcontrol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MTO_maze.dir/build.make CMakeFiles/MTO_maze.dir/src/motorcontrol.cpp.o
.PHONY : src/motorcontrol.cpp.o

src/motorcontrol.i: src/motorcontrol.cpp.i
.PHONY : src/motorcontrol.i

# target to preprocess a source file
src/motorcontrol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MTO_maze.dir/build.make CMakeFiles/MTO_maze.dir/src/motorcontrol.cpp.i
.PHONY : src/motorcontrol.cpp.i

src/motorcontrol.s: src/motorcontrol.cpp.s
.PHONY : src/motorcontrol.s

# target to generate assembly for a file
src/motorcontrol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MTO_maze.dir/build.make CMakeFiles/MTO_maze.dir/src/motorcontrol.cpp.s
.PHONY : src/motorcontrol.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MTO_maze"
	@echo "... include/sources/cell.o"
	@echo "... include/sources/cell.i"
	@echo "... include/sources/cell.s"
	@echo "... include/sources/maze.o"
	@echo "... include/sources/maze.i"
	@echo "... include/sources/maze.s"
	@echo "... include/sources/utils.o"
	@echo "... include/sources/utils.i"
	@echo "... include/sources/utils.s"
	@echo "... src/main_jen.o"
	@echo "... src/main_jen.i"
	@echo "... src/main_jen.s"
	@echo "... src/motorcontrol.o"
	@echo "... src/motorcontrol.i"
	@echo "... src/motorcontrol.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

